export type Lesson = { slug: string; title: string; level: "Beginner" | "Intermediate" | "Advanced"; minutes: number; summary: string; body: string[] };

export const LESSONS: Lesson[] = [
  {
    slug: "how-fixed-term-plans-work",
    title: "How fixed-term investment plans work",
    level: "Beginner",
    minutes: 4,
    summary: "What the return percentage, term and payout schedule mean, and how to compare two plans fairly.",
    body: [
      "A fixed-term plan locks an amount of USDT for a set number of days and pays a stated total return. Two plans with the same headline return can behave very differently depending on the term and the payout schedule.",
      "## Total return versus daily rate",
      "A 30-day plan paying 9% total pays 0.30% per day. A 90-day plan paying 21% total pays about 0.23% per day. Always divide the total return by the term to compare like with like.",
      "## Daily versus maturity payout",
      "Daily plans credit profit every 24 hours, which you can withdraw or reinvest immediately. Maturity plans pay everything on the last day. Daily payouts give flexibility; maturity plans usually offer a slightly higher total.",
      "## Capital back",
      "Plans marked 'capital returned' give your principal back at the end. Plans that say 'included in return' pay a larger figure that already contains your capital. Check which one you are looking at before comparing returns.",
    ],
  },
  {
    slug: "cloud-mining-explained",
    title: "Cloud mining explained",
    level: "Beginner",
    minutes: 5,
    summary: "Why you can mine without hardware, what hashrate means, and how maintenance fees affect your payout.",
    body: [
      "Cloud mining lets you rent a share of a professionally run mining facility. You pay for a fixed amount of hashpower for a fixed term and receive a share of what that hashpower produces.",
      "## Hashrate",
      "Hashrate is the amount of computing work your contract contributes. More hashrate means a larger share of the output. On PlutoVest each contract shows its hashrate and the estimated daily output in US dollars.",
      "## Maintenance fees",
      "Facilities cost money to run: electricity, cooling and staff. The maintenance fee is deducted from gross output before your payout. The daily figure shown on each contract is already net of this fee.",
      "## Payout assets",
      "PlutoVest pays mining output in Tether Gold (XAUT) or XRP. Output is valued in dollars each day and converted at the market rate at settlement, so the number of tokens you receive varies with price.",
    ],
  },
  {
    slug: "tether-gold-basics",
    title: "Tether Gold (XAUT): digital ownership of physical gold",
    level: "Beginner",
    minutes: 3,
    summary: "What XAUT represents, why it tracks the gold price and how it fits in a portfolio.",
    body: [
      "XAUT is a token where each unit represents one troy ounce of physical gold held in a vault. Its price follows the gold spot price, which is why it is often used as a lower-volatility store of value alongside cryptocurrencies.",
      "## Why mine into gold?",
      "Receiving mining payouts in XAUT means your daily output is converted into an asset whose price is driven by the gold market rather than crypto sentiment. Many members use it to lock in value as it is earned.",
      "## Holding and withdrawing",
      "XAUT sits in your PlutoVest wallet like any other asset. You can hold it, watch its value on the Markets page, or withdraw it to an external ERC20 wallet.",
    ],
  },
  {
    slug: "reading-market-data",
    title: "Reading the markets page",
    level: "Intermediate",
    minutes: 4,
    summary: "Price, 24-hour change, market cap, volume and sparklines, and what each tells you.",
    body: [
      "## Price and 24h change",
      "The price is the current market rate in US dollars. The 24-hour change shows how far it has moved since the same time yesterday. A large move in either direction means higher volatility.",
      "## Market cap and volume",
      "Market cap is price multiplied by circulating supply and gives a sense of an asset's size. Volume shows how much was traded in 24 hours; low volume relative to market cap can mean sharper price swings.",
      "## Sparklines",
      "The small chart is the last seven days of price. Use it to see the trend at a glance, not to time entries. Long-term plans care far more about the term than about a single day's movement.",
    ],
  },
  {
    slug: "portfolio-allocation",
    title: "Building a balanced allocation",
    level: "Intermediate",
    minutes: 6,
    summary: "How to split capital between investment plans, mining, property and cash so no single outcome hurts too much.",
    body: [
      "Diversification is the only free lunch in investing. Spreading capital across products with different drivers reduces the damage when one underperforms.",
      "## A simple framework",
      "Keep a cash buffer in USDT for withdrawals and opportunities. Put the core of your capital in plans whose terms you are comfortable waiting out. Add mining for daily income in XAUT or XRP, and property for yield that is less correlated with crypto prices.",
      "## Laddering terms",
      "Rather than one large 90-day plan, consider three plans that mature at different times. Laddering means something is always maturing, giving you regular access to capital without breaking a term.",
      "## Rebalancing",
      "Once a quarter, look at the allocation chart on the Assets page. If one bucket has grown far beyond its target, move some of the profit into the others.",
    ],
  },
  {
    slug: "security-checklist",
    title: "Account security checklist",
    level: "Beginner",
    minutes: 3,
    summary: "Ten habits that keep your account and your withdrawals safe.",
    body: [
      "Use a unique password of at least twelve characters and store it in a password manager. Never reuse a password from another site.",
      "Bookmark the real PlutoVest address and always sign in from the bookmark. Phishing sites copy login pages exactly; the address bar is the only reliable check.",
      "PlutoVest staff will never ask for your password, seed phrase or a payment to 'unlock' funds. Report any such message through a support ticket.",
      "Before withdrawing, send a small test amount to a new address first. Copy addresses; never type them by hand.",
      "Complete identity verification early so a withdrawal is never delayed when you need funds.",
      "Keep your email account secure with two-factor authentication; it is the recovery path for your PlutoVest account.",
    ],
  },
  {
    slug: "understanding-loans",
    title: "Borrowing responsibly",
    level: "Advanced",
    minutes: 4,
    summary: "When a loan makes sense, how fixed interest is calculated and how to plan repayment.",
    body: [
      "PlutoVest loans charge a fixed percentage of the principal for the whole term. There is no compounding and no early-repayment penalty, so the cost is known before you accept.",
      "## When it makes sense",
      "Borrowing to bridge a short-term cash need, while your capital keeps earning in a plan that has not matured, can be cheaper than exiting early. Borrowing to chase a return higher than the interest rate adds risk and should be sized conservatively.",
      "## Planning repayment",
      "Repayments come from your USDT balance. Match the loan term to a plan that matures before the due date so the capital is available, and repay in parts whenever profit lands to reduce what is outstanding.",
    ],
  },
];
